---
kind: Service
apiVersion: v1
metadata:
  name: k8s-demo
spec:
  type: LoadBalancer
  selector:
    app: k8s-demo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
      - name: nginx
        image: enzobarrett/k8s-demo
        ports:
        - containerPort: 80
          protocol: TCP
