name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Generate Short SHA
        id: shortsha
        run: |
          id=$(echo ${{ github.sha }} | head -c7)
          echo "::set-output name=id::$id"
        
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: enzobarrett/k8s-demo:${{ steps.shortsha.outputs.id }}
          
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save aea8a723-a77a-43f9-a56f-d87cbde0757b
